# Generated by Django 5.0.14 on 2026-08-15 06:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_workspace_is_public_workspace_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='is_public',
        ),
        migrations.AddField(
            model_name='workspace',
            name='mode',
            field=models.CharField(choices=[('individual', 'Individual'), ('room', 'Room')], default='individual', max_length=20),
        ),
        migrations.CreateModel(
            name='WorkspaceInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invites', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invites', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='core.workspace')),
            ],
            options={
                'unique_together': {('workspace', 'receiver')},
            },
        ),
    ]
