# Generated by Django 5.0.14 on 2026-08-15 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_workspace_is_public_workspace_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
